apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tekton-pipeline-demo-cluster
  region: eu-west-1
  version: "1.27"
  tags:
    project: tekton-pipeline-demo

availabilityZones: ["eu-west-1a", "eu-west-1b", "eu-west-1c"]

managedNodeGroups:
  - name: worker-ng-1
    instanceType: m5.large
    desiredCapacity: 3
    volumeSize: 73
    labels:
      role: workers
    tags:
      project: tekton-pipeline-demo
