apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: chartmuseum
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/tags: Project=tekton-pipeline-demo
    alb.ingress.kubernetes.io/security-groups: {{ .Values.chartmuseum.ingress.securityGroup }}
  name: chartmuseum
  namespace: support
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: chartmuseum
            port:
              number: 8080
        path: /
        pathType: Prefix
