apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-webhook-listener
  namespace: apps-build
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/tags: Project=tekton-pipeline-demo
    alb.ingress.kubernetes.io/group.name: webhook
    alb.ingress.kubernetes.io/security-groups: {{ .Values.triggers.ingress.securityGroup }}
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: el-codecommit-listener-interceptor
            port:
              number: 8080
        path: /
        pathType: Prefix
