region: "eu-west-1"
accountId: "190702572683"
allowedIpRange: "213.233.88.212/32"
chartmuseum:
  ingress:
    securityGroup: "sg-01dd64e517f1d12ee"
dashboard:
  ingress:
    securityGroup: "sg-0b299c13f753f0577"
pipelines:
  codeRepo:
    username: "b.mutiu%40deepsea.ai-at-190702572683"
    usernameRaw: "b.mutiu@deepsea.ai-at-190702572683"
    password: "LfUsSH3G85%2FS%2FRYPoUIqeCnevX4hCPvTWNjeYxioZJk%3D"
    passwordRaw: "LfUsSH3G85/S/RYPoUIqeCnevX4hCPvTWNjeYxioZJk="
triggers:
  ingress:
    securityGroup: "sg-0748bfb49a4a2d15d"
