apiVersion: v1
kind: Secret
metadata:
  name: codecommit-credentials
  namespace: argocd
type: Opaque
stringData:
  username: {{ .Values.pipelines.codeRepo.usernameRaw }}
  password: {{ .Values.pipelines.codeRepo.passwordRaw }}
